use std::{collections::HashMap, fs, path::Path};
use vsa_foundation::{Id, VsaError, VsaResult};
use vsa_studio::VertexDefinition;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WebMode {
    Static,
    Dynamic,
    App,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WebRoute {
    pub path: String,
    pub title: String,
    pub component: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeBinding {
    pub capability: String,
    pub preferred_target: String,
}

#[derive(Debug, Clone)]
pub struct WebProject {
    pub id: Id,
    pub mode: WebMode,
    pub routes: Vec<WebRoute>,
    pub bindings: Vec<RuntimeBinding>,
    pub metadata: HashMap<String, String>,
}

impl WebProject {
    pub fn new(mode: WebMode) -> Self {
        Self {
            id: Id::new("web"),
            mode,
            routes: vec![],
            bindings: vec![],
            metadata: HashMap::new(),
        }
    }
}

pub fn render_static_site(
    def: &VertexDefinition,
    project: &WebProject,
    out_dir: &Path,
) -> VsaResult<()> {
    if project.mode != WebMode::Static {
        return Err(VsaError::Invalid(
            "render_static_site requires Static mode".into(),
        ));
    }
    fs::create_dir_all(out_dir).map_err(|e| VsaError::Io(e.to_string()))?;
    let mut nav = String::new();
    for r in &project.routes {
        nav.push_str(&format!(
            "<a href=\"{}\">{}</a> ",
            r.path,
            html_escape(&r.title)
        ));
    }
    let html = format!(
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>{}</title></head>\
         <body><nav>{}</nav><main><h1>{}</h1><p>Generated by VSA Static Web Workspace.</p></main></body></html>",
        html_escape(&def.name),
        nav,
        html_escape(&def.name)
    );
    fs::write(out_dir.join("index.html"), html).map_err(|e| VsaError::Io(e.to_string()))
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};
    use vsa_studio::{ProjectKind, VertexDefinition};
    #[test]
    fn renders_static_index() {
        let def = VertexDefinition::new("Hello", ProjectKind::StaticWebsite);
        let mut p = WebProject::new(WebMode::Static);
        p.routes.push(WebRoute {
            path: "/".into(),
            title: "Home".into(),
            component: "home".into(),
        });
        let dir = std::env::temp_dir().join(format!(
            "vsa-web-{}",
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        render_static_site(&def, &p, &dir).unwrap();
        assert!(dir.join("index.html").exists());
        let _ = std::fs::remove_dir_all(dir);
    }
}
