[workspace]
resolver = "2"
members = [
    "core"
]

[workspace.package]
edition = "2021"
license = "UNLICENSED"
authors = ["Vertex"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
bytes = "1"
dashmap = "6"
parking_lot = "0.12"
smallvec = "1"
bitflags = "2"
crc32fast = "1"
