pub mod backend;
pub mod capability;
pub mod error;
pub mod ingress;
pub mod ir;
pub mod observability;
pub mod optimizer;
pub mod package;
pub mod parser;
pub mod reinforcement;
pub mod runtime;
pub mod scheduler;
pub mod security;
pub mod storage;
pub mod transport;
pub mod validator;

pub use error::{VxnError, VxnResult};
pub use ir::{Instruction, Program, Value};
pub use runtime::{ExecutionResult, Runtime};
